/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user/route'
import { Route as StoreRouteRouteImport } from './routes/_store/route'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreOffersRouteImport } from './routes/_store/offers'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as UserAuthenticatedRouteRouteImport } from './routes/user/_authenticated/route'
import { Route as UserAuthenticatedIndexRouteImport } from './routes/user/_authenticated/index'

const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const UserAuthenticatedSettingsRouteLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings',
)()
const UserAuthenticatedUsersIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/users/',
)()
const UserAuthenticatedSettingsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings/',
)()
const UserAuthenticatedProductsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/products/',
)()
const UserAuthenticatedOrdersIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/orders/',
)()
const UserAuthenticatedHelpCenterIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/help-center/',
)()
const UserAuthenticatedDraftsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/drafts/',
)()
const UserAuthenticatedChatsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/chats/',
)()
const UserAuthenticatedAppsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/apps/',
)()
const UserAuthenticatedAcheckoutsIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/acheckouts/',
)()
const UserAuthenticatedSettingsNotificationsLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings/notifications',
)()
const UserAuthenticatedSettingsDisplayLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings/display',
)()
const UserAuthenticatedSettingsAppearanceLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings/appearance',
)()
const UserAuthenticatedSettingsAccountLazyRouteImport = createFileRoute(
  '/user/_authenticated/settings/account',
)()
const UserAuthenticatedProductsSectionIndexLazyRouteImport = createFileRoute(
  '/user/_authenticated/products/$section/',
)()

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRouteRoute = StoreRouteRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRouteRoute,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const StoreOffersRoute = StoreOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => StoreRouteRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const UserAuthenticatedRouteRoute = UserAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAuthenticatedIndexRoute = UserAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserAuthenticatedRouteRoute,
} as any)
const UserAuthenticatedSettingsRouteLazyRoute =
  UserAuthenticatedSettingsRouteLazyRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/route.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedUsersIndexLazyRoute =
  UserAuthenticatedUsersIndexLazyRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/users/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedSettingsIndexLazyRoute =
  UserAuthenticatedSettingsIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserAuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedProductsIndexLazyRoute =
  UserAuthenticatedProductsIndexLazyRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedOrdersIndexLazyRoute =
  UserAuthenticatedOrdersIndexLazyRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/orders/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedHelpCenterIndexLazyRoute =
  UserAuthenticatedHelpCenterIndexLazyRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedDraftsIndexLazyRoute =
  UserAuthenticatedDraftsIndexLazyRouteImport.update({
    id: '/drafts/',
    path: '/drafts/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/drafts/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedChatsIndexLazyRoute =
  UserAuthenticatedChatsIndexLazyRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/chats/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedAppsIndexLazyRoute =
  UserAuthenticatedAppsIndexLazyRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/apps/index.lazy').then((d) => d.Route),
  )
const UserAuthenticatedAcheckoutsIndexLazyRoute =
  UserAuthenticatedAcheckoutsIndexLazyRouteImport.update({
    id: '/acheckouts/',
    path: '/acheckouts/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/acheckouts/index.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedSettingsNotificationsLazyRoute =
  UserAuthenticatedSettingsNotificationsLazyRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => UserAuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedSettingsDisplayLazyRoute =
  UserAuthenticatedSettingsDisplayLazyRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => UserAuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedSettingsAppearanceLazyRoute =
  UserAuthenticatedSettingsAppearanceLazyRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => UserAuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedSettingsAccountLazyRoute =
  UserAuthenticatedSettingsAccountLazyRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => UserAuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )
const UserAuthenticatedProductsSectionIndexLazyRoute =
  UserAuthenticatedProductsSectionIndexLazyRouteImport.update({
    id: '/products/$section/',
    path: '/products/$section/',
    getParentRoute: () => UserAuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/user/_authenticated/products/$section/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/user': typeof UserAuthenticatedRouteRouteWithChildren
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof StoreAboutRoute
  '/offers': typeof StoreOffersRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/user/settings': typeof UserAuthenticatedSettingsRouteLazyRouteWithChildren
  '/user/': typeof UserAuthenticatedIndexRoute
  '/user/settings/account': typeof UserAuthenticatedSettingsAccountLazyRoute
  '/user/settings/appearance': typeof UserAuthenticatedSettingsAppearanceLazyRoute
  '/user/settings/display': typeof UserAuthenticatedSettingsDisplayLazyRoute
  '/user/settings/notifications': typeof UserAuthenticatedSettingsNotificationsLazyRoute
  '/user/acheckouts/': typeof UserAuthenticatedAcheckoutsIndexLazyRoute
  '/user/apps/': typeof UserAuthenticatedAppsIndexLazyRoute
  '/user/chats/': typeof UserAuthenticatedChatsIndexLazyRoute
  '/user/drafts/': typeof UserAuthenticatedDraftsIndexLazyRoute
  '/user/help-center/': typeof UserAuthenticatedHelpCenterIndexLazyRoute
  '/user/orders/': typeof UserAuthenticatedOrdersIndexLazyRoute
  '/user/products/': typeof UserAuthenticatedProductsIndexLazyRoute
  '/user/settings/': typeof UserAuthenticatedSettingsIndexLazyRoute
  '/user/users/': typeof UserAuthenticatedUsersIndexLazyRoute
  '/user/products/$section/': typeof UserAuthenticatedProductsSectionIndexLazyRoute
}
export interface FileRoutesByTo {
  '/user': typeof UserAuthenticatedIndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof StoreAboutRoute
  '/offers': typeof StoreOffersRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof StoreIndexRoute
  '/user/settings/account': typeof UserAuthenticatedSettingsAccountLazyRoute
  '/user/settings/appearance': typeof UserAuthenticatedSettingsAppearanceLazyRoute
  '/user/settings/display': typeof UserAuthenticatedSettingsDisplayLazyRoute
  '/user/settings/notifications': typeof UserAuthenticatedSettingsNotificationsLazyRoute
  '/user/acheckouts': typeof UserAuthenticatedAcheckoutsIndexLazyRoute
  '/user/apps': typeof UserAuthenticatedAppsIndexLazyRoute
  '/user/chats': typeof UserAuthenticatedChatsIndexLazyRoute
  '/user/drafts': typeof UserAuthenticatedDraftsIndexLazyRoute
  '/user/help-center': typeof UserAuthenticatedHelpCenterIndexLazyRoute
  '/user/orders': typeof UserAuthenticatedOrdersIndexLazyRoute
  '/user/products': typeof UserAuthenticatedProductsIndexLazyRoute
  '/user/settings': typeof UserAuthenticatedSettingsIndexLazyRoute
  '/user/users': typeof UserAuthenticatedUsersIndexLazyRoute
  '/user/products/$section': typeof UserAuthenticatedProductsSectionIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteRouteWithChildren
  '/user': typeof UserRouteRouteWithChildren
  '/user/_authenticated': typeof UserAuthenticatedRouteRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_store/about': typeof StoreAboutRoute
  '/_store/offers': typeof StoreOffersRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_store/': typeof StoreIndexRoute
  '/user/_authenticated/settings': typeof UserAuthenticatedSettingsRouteLazyRouteWithChildren
  '/user/_authenticated/': typeof UserAuthenticatedIndexRoute
  '/user/_authenticated/settings/account': typeof UserAuthenticatedSettingsAccountLazyRoute
  '/user/_authenticated/settings/appearance': typeof UserAuthenticatedSettingsAppearanceLazyRoute
  '/user/_authenticated/settings/display': typeof UserAuthenticatedSettingsDisplayLazyRoute
  '/user/_authenticated/settings/notifications': typeof UserAuthenticatedSettingsNotificationsLazyRoute
  '/user/_authenticated/acheckouts/': typeof UserAuthenticatedAcheckoutsIndexLazyRoute
  '/user/_authenticated/apps/': typeof UserAuthenticatedAppsIndexLazyRoute
  '/user/_authenticated/chats/': typeof UserAuthenticatedChatsIndexLazyRoute
  '/user/_authenticated/drafts/': typeof UserAuthenticatedDraftsIndexLazyRoute
  '/user/_authenticated/help-center/': typeof UserAuthenticatedHelpCenterIndexLazyRoute
  '/user/_authenticated/orders/': typeof UserAuthenticatedOrdersIndexLazyRoute
  '/user/_authenticated/products/': typeof UserAuthenticatedProductsIndexLazyRoute
  '/user/_authenticated/settings/': typeof UserAuthenticatedSettingsIndexLazyRoute
  '/user/_authenticated/users/': typeof UserAuthenticatedUsersIndexLazyRoute
  '/user/_authenticated/products/$section/': typeof UserAuthenticatedProductsSectionIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/user'
    | '/otp'
    | '/sign-in'
    | '/about'
    | '/offers'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/user/settings'
    | '/user/'
    | '/user/settings/account'
    | '/user/settings/appearance'
    | '/user/settings/display'
    | '/user/settings/notifications'
    | '/user/acheckouts/'
    | '/user/apps/'
    | '/user/chats/'
    | '/user/drafts/'
    | '/user/help-center/'
    | '/user/orders/'
    | '/user/products/'
    | '/user/settings/'
    | '/user/users/'
    | '/user/products/$section/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/user'
    | '/otp'
    | '/sign-in'
    | '/about'
    | '/offers'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/user/settings/account'
    | '/user/settings/appearance'
    | '/user/settings/display'
    | '/user/settings/notifications'
    | '/user/acheckouts'
    | '/user/apps'
    | '/user/chats'
    | '/user/drafts'
    | '/user/help-center'
    | '/user/orders'
    | '/user/products'
    | '/user/settings'
    | '/user/users'
    | '/user/products/$section'
  id:
    | '__root__'
    | '/_store'
    | '/user'
    | '/user/_authenticated'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_store/about'
    | '/_store/offers'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_store/'
    | '/user/_authenticated/settings'
    | '/user/_authenticated/'
    | '/user/_authenticated/settings/account'
    | '/user/_authenticated/settings/appearance'
    | '/user/_authenticated/settings/display'
    | '/user/_authenticated/settings/notifications'
    | '/user/_authenticated/acheckouts/'
    | '/user/_authenticated/apps/'
    | '/user/_authenticated/chats/'
    | '/user/_authenticated/drafts/'
    | '/user/_authenticated/help-center/'
    | '/user/_authenticated/orders/'
    | '/user/_authenticated/products/'
    | '/user/_authenticated/settings/'
    | '/user/_authenticated/users/'
    | '/user/_authenticated/products/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRouteRoute: typeof StoreRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/offers': {
      id: '/_store/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof StoreOffersRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_authenticated': {
      id: '/user/_authenticated'
      path: ''
      fullPath: '/user'
      preLoaderRoute: typeof UserAuthenticatedRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/user/_authenticated/': {
      id: '/user/_authenticated/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserAuthenticatedIndexRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/settings': {
      id: '/user/_authenticated/settings'
      path: '/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserAuthenticatedSettingsRouteLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/users/': {
      id: '/user/_authenticated/users/'
      path: '/users'
      fullPath: '/user/users/'
      preLoaderRoute: typeof UserAuthenticatedUsersIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/settings/': {
      id: '/user/_authenticated/settings/'
      path: '/'
      fullPath: '/user/settings/'
      preLoaderRoute: typeof UserAuthenticatedSettingsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedSettingsRouteLazyRoute
    }
    '/user/_authenticated/products/': {
      id: '/user/_authenticated/products/'
      path: '/products'
      fullPath: '/user/products/'
      preLoaderRoute: typeof UserAuthenticatedProductsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/orders/': {
      id: '/user/_authenticated/orders/'
      path: '/orders'
      fullPath: '/user/orders/'
      preLoaderRoute: typeof UserAuthenticatedOrdersIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/help-center/': {
      id: '/user/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/user/help-center/'
      preLoaderRoute: typeof UserAuthenticatedHelpCenterIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/drafts/': {
      id: '/user/_authenticated/drafts/'
      path: '/drafts'
      fullPath: '/user/drafts/'
      preLoaderRoute: typeof UserAuthenticatedDraftsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/chats/': {
      id: '/user/_authenticated/chats/'
      path: '/chats'
      fullPath: '/user/chats/'
      preLoaderRoute: typeof UserAuthenticatedChatsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/apps/': {
      id: '/user/_authenticated/apps/'
      path: '/apps'
      fullPath: '/user/apps/'
      preLoaderRoute: typeof UserAuthenticatedAppsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/acheckouts/': {
      id: '/user/_authenticated/acheckouts/'
      path: '/acheckouts'
      fullPath: '/user/acheckouts/'
      preLoaderRoute: typeof UserAuthenticatedAcheckoutsIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
    '/user/_authenticated/settings/notifications': {
      id: '/user/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/user/settings/notifications'
      preLoaderRoute: typeof UserAuthenticatedSettingsNotificationsLazyRouteImport
      parentRoute: typeof UserAuthenticatedSettingsRouteLazyRoute
    }
    '/user/_authenticated/settings/display': {
      id: '/user/_authenticated/settings/display'
      path: '/display'
      fullPath: '/user/settings/display'
      preLoaderRoute: typeof UserAuthenticatedSettingsDisplayLazyRouteImport
      parentRoute: typeof UserAuthenticatedSettingsRouteLazyRoute
    }
    '/user/_authenticated/settings/appearance': {
      id: '/user/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/user/settings/appearance'
      preLoaderRoute: typeof UserAuthenticatedSettingsAppearanceLazyRouteImport
      parentRoute: typeof UserAuthenticatedSettingsRouteLazyRoute
    }
    '/user/_authenticated/settings/account': {
      id: '/user/_authenticated/settings/account'
      path: '/account'
      fullPath: '/user/settings/account'
      preLoaderRoute: typeof UserAuthenticatedSettingsAccountLazyRouteImport
      parentRoute: typeof UserAuthenticatedSettingsRouteLazyRoute
    }
    '/user/_authenticated/products/$section/': {
      id: '/user/_authenticated/products/$section/'
      path: '/products/$section'
      fullPath: '/user/products/$section/'
      preLoaderRoute: typeof UserAuthenticatedProductsSectionIndexLazyRouteImport
      parentRoute: typeof UserAuthenticatedRouteRoute
    }
  }
}

interface StoreRouteRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreOffersRoute: typeof StoreOffersRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteRouteChildren: StoreRouteRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreOffersRoute: StoreOffersRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteRouteWithChildren = StoreRouteRoute._addFileChildren(
  StoreRouteRouteChildren,
)

interface UserAuthenticatedSettingsRouteLazyRouteChildren {
  UserAuthenticatedSettingsAccountLazyRoute: typeof UserAuthenticatedSettingsAccountLazyRoute
  UserAuthenticatedSettingsAppearanceLazyRoute: typeof UserAuthenticatedSettingsAppearanceLazyRoute
  UserAuthenticatedSettingsDisplayLazyRoute: typeof UserAuthenticatedSettingsDisplayLazyRoute
  UserAuthenticatedSettingsNotificationsLazyRoute: typeof UserAuthenticatedSettingsNotificationsLazyRoute
  UserAuthenticatedSettingsIndexLazyRoute: typeof UserAuthenticatedSettingsIndexLazyRoute
}

const UserAuthenticatedSettingsRouteLazyRouteChildren: UserAuthenticatedSettingsRouteLazyRouteChildren =
  {
    UserAuthenticatedSettingsAccountLazyRoute:
      UserAuthenticatedSettingsAccountLazyRoute,
    UserAuthenticatedSettingsAppearanceLazyRoute:
      UserAuthenticatedSettingsAppearanceLazyRoute,
    UserAuthenticatedSettingsDisplayLazyRoute:
      UserAuthenticatedSettingsDisplayLazyRoute,
    UserAuthenticatedSettingsNotificationsLazyRoute:
      UserAuthenticatedSettingsNotificationsLazyRoute,
    UserAuthenticatedSettingsIndexLazyRoute:
      UserAuthenticatedSettingsIndexLazyRoute,
  }

const UserAuthenticatedSettingsRouteLazyRouteWithChildren =
  UserAuthenticatedSettingsRouteLazyRoute._addFileChildren(
    UserAuthenticatedSettingsRouteLazyRouteChildren,
  )

interface UserAuthenticatedRouteRouteChildren {
  UserAuthenticatedSettingsRouteLazyRoute: typeof UserAuthenticatedSettingsRouteLazyRouteWithChildren
  UserAuthenticatedIndexRoute: typeof UserAuthenticatedIndexRoute
  UserAuthenticatedAcheckoutsIndexLazyRoute: typeof UserAuthenticatedAcheckoutsIndexLazyRoute
  UserAuthenticatedAppsIndexLazyRoute: typeof UserAuthenticatedAppsIndexLazyRoute
  UserAuthenticatedChatsIndexLazyRoute: typeof UserAuthenticatedChatsIndexLazyRoute
  UserAuthenticatedDraftsIndexLazyRoute: typeof UserAuthenticatedDraftsIndexLazyRoute
  UserAuthenticatedHelpCenterIndexLazyRoute: typeof UserAuthenticatedHelpCenterIndexLazyRoute
  UserAuthenticatedOrdersIndexLazyRoute: typeof UserAuthenticatedOrdersIndexLazyRoute
  UserAuthenticatedProductsIndexLazyRoute: typeof UserAuthenticatedProductsIndexLazyRoute
  UserAuthenticatedUsersIndexLazyRoute: typeof UserAuthenticatedUsersIndexLazyRoute
  UserAuthenticatedProductsSectionIndexLazyRoute: typeof UserAuthenticatedProductsSectionIndexLazyRoute
}

const UserAuthenticatedRouteRouteChildren: UserAuthenticatedRouteRouteChildren =
  {
    UserAuthenticatedSettingsRouteLazyRoute:
      UserAuthenticatedSettingsRouteLazyRouteWithChildren,
    UserAuthenticatedIndexRoute: UserAuthenticatedIndexRoute,
    UserAuthenticatedAcheckoutsIndexLazyRoute:
      UserAuthenticatedAcheckoutsIndexLazyRoute,
    UserAuthenticatedAppsIndexLazyRoute: UserAuthenticatedAppsIndexLazyRoute,
    UserAuthenticatedChatsIndexLazyRoute: UserAuthenticatedChatsIndexLazyRoute,
    UserAuthenticatedDraftsIndexLazyRoute:
      UserAuthenticatedDraftsIndexLazyRoute,
    UserAuthenticatedHelpCenterIndexLazyRoute:
      UserAuthenticatedHelpCenterIndexLazyRoute,
    UserAuthenticatedOrdersIndexLazyRoute:
      UserAuthenticatedOrdersIndexLazyRoute,
    UserAuthenticatedProductsIndexLazyRoute:
      UserAuthenticatedProductsIndexLazyRoute,
    UserAuthenticatedUsersIndexLazyRoute: UserAuthenticatedUsersIndexLazyRoute,
    UserAuthenticatedProductsSectionIndexLazyRoute:
      UserAuthenticatedProductsSectionIndexLazyRoute,
  }

const UserAuthenticatedRouteRouteWithChildren =
  UserAuthenticatedRouteRoute._addFileChildren(
    UserAuthenticatedRouteRouteChildren,
  )

interface UserRouteRouteChildren {
  UserAuthenticatedRouteRoute: typeof UserAuthenticatedRouteRouteWithChildren
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAuthenticatedRouteRoute: UserAuthenticatedRouteRouteWithChildren,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  StoreRouteRoute: StoreRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
